### ISSUE TITLE
couldn't find "libAzul.so"

### ISSUE THREAD

**Issue by tyzero** [phunware/maas-mapping-android-sdk#43]
Hello,  there is a problem always happen to me.
 **libAzul.so** currently only  in **armeabi** directory, so I got crash issue when my app is using x86 or arm64-v8a .  I need to force my app to using armeabi but this may cause other issue. can you team provide a  libAzul.so for  arm64-v8a and  x86 ?, thanks.

**Comment by astolzberg** [comment]
@tyzero which architectures are you building for?

**Comment by tyzero** [comment]
@astolzberg arm64-v8a and x86

**Comment by astolzberg** [comment]
Which SDKs are you using? Just Location and Mapping? I'd recommend trying the latest versions of both (v3.4.0 was released last week).

**Comment by avakkachen** [comment]
Location SDK  does not support x86 architecture as of now. 
But the latest version (Location SDK 3.7.5) does have support for arm64-v8a
