### ISSUE TITLE
Map - Blue dot - Not showing up

### ISSUE THREAD

**Issue by mbalajee** [phunware/maas-mapping-android-sdk#67]
With the below versions, blue dot never shows up while within the geofence and near the beacon,

pw_engagement=3.6.1
pw_beacon_location_manager=3.5.5
pw_mapping=3.9.0
pw_location_provider=3.7.0

**Comment by avakkachen** [comment]
Can you try upgrading to Location SDK 3.7.1. 
Version 3.7.0 had an issue in the native layer which was resolved in 3.7.1.

**Comment by mbalajee** [comment]
Yeah it is fixed in 3.7.1.  Will there be a SDK update for below orientation issue?
1.  User is unable to pan the map in FOLLOW_ME mode
2. Map is not rightly oriented based on route and user's walking direction

**Comment by avakkachen** [comment]
Can you let us know the behavior / error you're seeing during panning in FollowMe mode.

**Comment by avakkachen** [comment]
Closing this ticket as the original issue 'Blue dot - Not showing up' is fixed in Location SDK 3.7.1.
