### ISSUE TITLE
Accessing DRAFT version of Map

### ISSUE THREAD

**Issue by mbalajee** [phunware/maas-mapping-android-sdk#69]
Is there a way to get the Building object of Draft Map?  Tried with below options all of them returns only LIVE version,

PwCoreSession.getInstance().setEnvironment(PwCoreSession.Environment.TEST);
PwCoreSession.getInstance().setEnvironment(PwCoreSession.Environment.DEV);
PwCoreSession.getInstance().setEnvironment(PwCoreSession.Environment.STAGE);

**Comment by tstump-phunware** [comment]
@mbalajee Not at this time. 

The DRAFT version of a building is not exposed through our SDKs. Changes in the DRAFT version can only be viewed in our Locate fingerprinting app (iOS only).
